### ISSUE TITLE
Bizarre check failure on @.midas.dasm

### ISSUE THREAD

**Issue by tvrusso** [larsbrinkhoff/pdp10-its-disassembler#48]
I am building this as it is a submodule of its (specifically, at commit 9d5d4a3).  Building on FreeBSD, the compilation goes just fine, but then make fails when comparing "@.midas.dasm" to "test/@.midas.dasm".  

I checked manually by running:

 ./dis10 -D774000 -Sall samples/@.midas > @.midas.dasm

and then diffing the files.  They appear to differ primarily by the names of labels, and not in substantive ways (attaching the diff of the file produced by the command above and the one in test)

None of the other checks fail.

If I ignore this failure and redo the make in the parent its project, it skips over dasm and everything else proceeds just fine, building the simh simulator and building the its image. 

[at.midas.dasm.diff.txt](https://github.com/larsbrinkhoff/pdp10-its-disassembler/files/4209100/at.midas.dasm.diff.txt)

**Comment by atsampson** [comment]
That looks like the sorting bug I fixed in [this commit](https://github.com/larsbrinkhoff/pdp10-its-disassembler/commit/a4de58bc7df259f0864325b9306ee820c280b050) - I think the submodule in its is still at a version before that.

I've just tested building on a FreeBSD 12.1 machine and found a couple of unrelated problems (#49), but with those fixed the tests pass now.

**Comment by larsbrinkhoff** [comment]
Thanks.  I'll update the submodule when the fixes are merged.
